// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUtNHi30mLqyZPlvjF5-VrpFLVuUwoDVw',
    appId: '1:324882368247:web:2b038c5d79d0f6b9e5b5f2',
    messagingSenderId: '324882368247',
    projectId: 'epic-the-firebase',
    authDomain: 'epic-the-firebase.firebaseapp.com',
    storageBucket: 'epic-the-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUtNHi30mLqyZPlvjF5-VrpFLVuUwoDVw',
    appId: '1:324882368247:android:2b038c5d79d0f6b9e5b5f2',
    messagingSenderId: '324882368247',
    projectId: 'epic-the-firebase',
    storageBucket: 'epic-the-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUtNHi30mLqyZPlvjF5-VrpFLVuUwoDVw',
    appId: '1:324882368247:ios:2b038c5d79d0f6b9e5b5f2',
    messagingSenderId: '324882368247',
    projectId: 'epic-the-firebase',
    storageBucket: 'epic-the-firebase.appspot.com',
    iosBundleId: 'com.example.listas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUtNHi30mLqyZPlvjF5-VrpFLVuUwoDVw',
    appId: '1:324882368247:macos:2b038c5d79d0f6b9e5b5f2',
    messagingSenderId: '324882368247',
    projectId: 'epic-the-firebase',
    storageBucket: 'epic-the-firebase.appspot.com',
    iosBundleId: 'com.example.listas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUtNHi30mLqyZPlvjF5-VrpFLVuUwoDVw',
    appId: '1:324882368247:windows:2b038c5d79d0f6b9e5b5f2',
    messagingSenderId: '324882368247',
    projectId: 'epic-the-firebase',
    authDomain: 'epic-the-firebase.firebaseapp.com',
    storageBucket: 'epic-the-firebase.appspot.com',
  );
}
